mybatis:
  type-aliases-package: com.mycompany.myapp.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  #env
  port: 2333

concurrent:
  pool-size: 20


spring:
  dataSource:
    driver: com.ibm.db2.jcc.DB2Driver
    #env
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    #env
    username: test
    #env
    password: test
    #env
    maxActive: 20


logging:
  config: classpath:logback-spring.xml
  path: d:/aa/bb